### PR TITLE
Enhancements for Webapp

### PR DESCRIPTION
**Pull request by VLBHAT31**
This PR includes:
- Implemention of session for login.
- Changed colour of notification to yellow for successful detection and light ON.
- Edited the electricitystatus graph in index as well as electricitystatus page along with the table.
- Started the implementation of the db connection for user profile page, but was not successfully implemented.
- Also tried to implement the dynamic graph for ON-OFF graph but is not completed as the db connection has to be checked for dynamicity.

### CODE REVIEW

**Comment by kinderasteroid** [comment]
@VLBHAT31  Branch Has Conflicts. Can you Remove those Conflict Files i.e Cache Files and Re Init your PR?

**Comment by kinderasteroid** [comment]
@VLBHAT31 
image
I am Not able to Merge PR due to These Conflict Files

**Comment by VLBHAT31** [comment]
> @VLBHAT31 image I am Not able to Merge PR due to These Conflict Files

i removed those cache files and pushed here but its still showing like this why?

**Comment by kinderasteroid** [comment]
> > @VLBHAT31 image I am Not able to Merge PR due to These Conflict Files
> 
> i removed those cache files and pushed here but its still showing like this why?

Did you make Git rm?

**Comment by kinderasteroid** [comment]
@VLBHAT31 
image
Try This

**Comment by VLBHAT31** [comment]
> > > @VLBHAT31 image I am Not able to Merge PR due to These Conflict Files
> > 
> > 
> > i removed those cache files and pushed here but its still showing like this why?
> 
> Did you make Git rm?

yes

**Comment by VLBHAT31** [comment]
> @VLBHAT31 image Try This

i did this as well still its not going

**Comment by VLBHAT31** [comment]
Resolved the merge conflicts.

**Review by kinderasteroid — APPROVED** [review]
@VLBHAT31 Code is Approved

**Pull request merged**
